import { useMemo } from 'react'

let vocabMapCache = null

export function useVocabLookup() {
  return useMemo(() => {
    if (vocabMapCache) return vocabMapCache

    try {
      // Dynamic import would be better but for simplicity we use require-style
      // The vocab-index.js is generated by the build script
      const mod = import.meta.glob('../data/vocab-index.js', { eager: true })
      const key = Object.keys(mod)[0]
      if (key && mod[key]?.vocabMap) {
        vocabMapCache = mod[key].vocabMap
        return vocabMapCache
      }
    } catch (e) {
      // vocab index not yet built
    }

    return {}
  }, [])
}
